---
required: ["init_lib", "data_lib", "db", "passwd", "user_name", "host", "sock_path", "db_prefix", "startup_cmd"]
init_lib: /home/Squirrel/data/fuzz_root/mysql_init_lib
data_lib: /home/Squirrel/data/fuzz_root/global_data_lib_mysql
db: mysql
passwd: ''
user_name: root
host: localhost
sock_path: /home/for_showmap/mysql_for_showmap.sock
db_prefix: test
# It is important that the command should run on background
startup_cmd: "/usr/local/mysql/bin/mysqld --basedir=/usr/local/mysql --datadir=/usr/local/mysql/data --log-error=err_log.err --pid-file=/home/for_showmap/showmap_server_pid.pid --max-execution-time=1000 --socket=/home/for_showmap/mysql_for_showmap.sock &"
